# ansible-playbook -i ../inventories/exampleenv/inventory.ini playbooks/pb-example.yml -k -u "TESTUSER"

---

- name: "Example play"
  hosts: examplehosts
  vars:
    favcolor: blue
  vars_files:
    - ../vars/vars_Example_play.yml

  tasks:

  - name: 'This is just a placeholder'
    ansible.builtin.command: /bin/echo "{{ favcolor }}"